In [1]:
import numpy as np

In [2]:
array_2x2 = np.array([[1, 2],
                      [3, 4]])
print(array_2x2)

[[1 2]
 [3 4]]


In [3]:
rand_3x4 = np.random.rand(3, 4)
print(rand_3x4)

[[0.09240364 0.22248541 0.75366384 0.12301726]
 [0.52810867 0.37145745 0.13761142 0.51081707]
 [0.8156863  0.0338681  0.83486261 0.17723146]]


In [4]:
ones_array = np.ones((2, 3))
zeros_array = np.zeros((2, 3))
print(ones_array)
print(zeros_array)


[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
rand_6x3 = np.random.rand(6, 3)
x= rand_6x3.T
print(rand_6x3)
print(x)

[[0.34291835 0.62995574 0.4209744 ]
 [0.40899852 0.09300033 0.54058532]
 [0.81307109 0.97450609 0.3756099 ]
 [0.43548585 0.2482285  0.12794479]
 [0.52053964 0.06424129 0.65084704]
 [0.31935969 0.95992676 0.74026692]]
[[0.34291835 0.40899852 0.81307109 0.43548585 0.52053964 0.31935969]
 [0.62995574 0.09300033 0.97450609 0.2482285  0.06424129 0.95992676]
 [0.4209744  0.54058532 0.3756099  0.12794479 0.65084704 0.74026692]]


In [6]:
n, p, m = 3, 2, 4
A = np.random.rand(n, p)
B = np.random.rand(p, m)
C= np.dot(A, B)
print(A)
print(B)
print(C)

[[0.30459579 0.03329041]
 [0.66196674 0.74722013]
 [0.9542966  0.53772862]]
[[0.84545667 0.19573842 0.76534844 0.94092461]
 [0.09709146 0.57003699 0.83440596 0.73782078]]
[[0.26075476 0.07859787 0.26089964 0.31116404]
 [0.63221289 0.55551544 1.13012014 1.17417533]
 [0.85902528 0.49331771 1.17905338 1.29466851]]


In [7]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [8]:
%cd /content/drive/MyDrive
!mkdir -p git_repos
%cd git_repos


/content/drive/MyDrive
/content/drive/MyDrive/git_repos


In [10]:
!git clone https://github.com/Abdullah-Bamakhramah/data-science-toolkit.git
%cd data-science-toolkit


Cloning into 'data-science-toolkit'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 13 (delta 2), reused 4 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (13/13), done.
Resolving deltas: 100% (2/2), done.
/content/drive/MyDrive/git_repos/data-science-toolkit/data-science-toolkit


In [11]:
!git config --global user.name "Abdullah-Bamakhramah"
!git config --global user.email "24203474@siswa.um.edu.my"
!git config pull.rebase false
!git config --global core.editor true


In [16]:
!find /content/drive -name "tutorial3.ipynb"


/content/drive/MyDrive/Colab Notebooks/tutorial3.ipynb


In [17]:
!mv "/content/drive/MyDrive/Colab Notebooks/tutorial3.ipynb" "./"



In [18]:
!ls


numpytutorial.ipynb  python_basics.ipynb  README.md  tutorial3.ipynb


In [ ]:
!git add tutorial3.ipynb
!git commit -m "Added tutorial3 NumPy notebook"
!git push https://Abdullah-Bamakhramah:YOUR_TOKEN@github.com/Abdullah-Bamakhramah/data-science-toolkit.git main
